repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.10
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
        files: "^backend/"
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
        files: "^backend/"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.1.1
    hooks:
      - id: eslint
        files: "^frontend/.*\\.(js|ts|tsx)$"
        additional_dependencies:
          - "@angular-eslint/eslint-plugin"
          - "@typescript-eslint/eslint-plugin"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: "^frontend/.*\\.(js|ts|tsx|json|css|scss|html)$"
